### PR TITLE
support macos

### PR DESCRIPTION
**Pull request by xiaoxiaoleo**
RT

### CODE REVIEW

**Comment by mazen160** [comment]
Hi @xiaoxiaoleo ,

Thank you for the pull request!

Is firefox-security-toolkit currently not working on MacOS using the current state?

**Comment by xiaoxiaoleo** [comment]
Hi mazen, It works actually, however the directory are different.

**Comment by mazen160** [comment]
Thanks for checking.

How about using:
`which firefox`
Does it points to the correct Firefox binary?

**Comment by xiaoxiaoleo** [comment]
Nope..It's seem like  'which' command not show the correct info  in MacOS, because  Firefox-bin is inside the Firefox application bundle (/Applications/Firefox.app/).

**Comment by mazen160** [comment]
How about 
```bash
$ uname
```

The result should be `Darwin` in your machine, right?

**Comment by xiaoxiaoleo** [comment]
Yes, it's Darwin

**Comment by mazen160** [comment]
Hi @xiaoxiaoleo ,
Thank you again the PR. Nice additions!

I made minor modifications to your PR to detect if machine is MacOS for UX purposes.

Thanks!

**Comment by xiaoxiaoleo** [comment]
Great!

**Pull request merged**
